### ISSUE TITLE
IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by sunnyangazy** [thuml/iTransformer#1]
how to fix this problem

outputs = outputs[:, -self.args.pred_len:, f_dim:] IndexError: too many indices for tensor of dimension 2

**Comment by ZDandsomSP** [comment]
Hello, thank you for your comment, but could you please provide some more detailed information, such as the name of the script you executed, relevant configurations, and error location.

**Comment by ZDandsomSP** [comment]
Thank you for your feedback. We have just completed the merging of the model.

**Comment by binbinlan** [comment]
set output_attention == False ,will solve this problem.
