### ISSUE TITLE
Non-stationary Transformer??

### ISSUE THREAD

**Issue by lzmax888** [thuml/iTransformer#10]
There is a comment in your code

[# De-Normalization from Non-stationary Transformer](https://github.com/thuml/iTransformer/blob/c0f5b48fefd949c0216ef23d387d4d048dbc16d1/model/iTransformer.py#L63C11-L63C11)

but I can't find anything about it.

Thanks

**Comment by WenWeiTHU** [comment]
It means Series Stationarization of [NSformer](https://github.com/thuml/Nonstationary_Transformers), which works effectively for the stationary problem and has been generally adopted  by the current forecasting models.
