### ISSUE TITLE
Mixed frequency forecast with iTransformer?

### ISSUE THREAD

**Issue by kkckk1110** [thuml/iTransformer#102]
Hello, I found iTransformer really impressive and it had potentials for my own task. I have a question that, how can iTransformer be applied to mixed frequency data? That is, I hope to use multivariate daily features to predict a monthly variable. I think the capability of iTransformer to deal with multivariate features can help solve the problem. But I have a struggle with the essence of mixed frequency data. In this case, can iTransformer be applied and in which way? Thanks for your attention!

**Comment by WenWeiTHU** [comment]
Hi, since multivariate forecasting has the intrinsic problem of mixture frequency, it is better to regard each variate independently like iTransformer and use different embedding layers for varied variates if the frequency gap is quite large.
