### ISSUE TITLE
训练得到了奇奇怪怪的loss曲线

### ISSUE THREAD

**Issue by sunxiaoyao-git** [thuml/iTransformer#105]
作者您好，我用我的数据跑了您的模型代码，得到几个非常奇怪的loss曲线，您能帮忙给出几个优化的方向吗？数据已经做了standardscaler， 换了minmaxscaler也是很奇怪。
![image](https://github.com/user-attachments/assets/db6d9a9a-782b-461f-b0f1-1dd2b9b53f5e)
![image](https://github.com/user-attachments/assets/5502bb86-9125-4bee-bd25-f0e9749af3f7)

**Comment by WenWeiTHU** [comment]
您好，可以尝试更换学习率，或者根据数据自相关性确定预测的输入输出长度等
