### ISSUE TITLE
iTransformer论文中引入的PatchTST中的ECL预测结果与原PatchTST论文偏差较大

### ISSUE THREAD

**Issue by sweetheartstrawberry** [thuml/iTransformer#107]
您好，iTransformer论文中引入的PatchTST中的ECL预测结果和PatchTST原论文中的结果偏差较大是什么原因啊？引用的数据结果是自己重新跑了一遍PatchTST的结果吗？

**Comment by bigdata0** [comment]
PatchTST的回顾窗口很大，原文是这么说的
```
PatchTST/64 implies the
 number of input patches is 64, which uses the look-back window L = 512. PatchTST/42 means the
 number of input patches is 42, which has the default look-back window L = 336
```在PatchTST原论文中提供了ECL数据集中预测96步情况下采用不同回顾窗口长度下的可视化结果
![image](https://github.com/user-attachments/assets/7db13097-a820-416f-861d-b1af3149fc16)
iTransformer论文中对于输入96步预测未来96步的PatchTST的MSE结果是0.181，还是比较合理的。

**Comment by bigdata0** [comment]
PatchTST回顾窗口很大原文是这么说的：PatchTST/64 implies the
 number of input patches is 64, which uses the look-back window L = 512. PatchTST/42 means the
 number of input patches is 42, which has the default look-back window L = 336
在PatchTST原论文中提供了ECL数据集中预测96步情况下采用不同回顾窗口长度下的可视化结果
![image](https://github.com/user-attachments/assets/a0ffbca2-24f2-467c-b16b-cb8868bdaf50)
iTransformer论文中对于输入96步预测未来96步的PatchTST的MSE结果是0.181，还是比较合理的。
