### ISSUE TITLE
关于输入序列长度的问题

### ISSUE THREAD

**Issue by Schopenhauer-loves-Hegel** [thuml/iTransformer#109]
hello您好，我在序列预测方面不是非常了解，对于序列预测问题我有一个小小的疑问，您的工作中将N维时序变量的每一维通过FFN映射成embedding，然后对N个embedding做 self attention、layer norm等操作（这是我对模型的理解，如果有误请您指出）。FFN的输入维度就是一维时序变量的seq_len，也就是说整个模型在预测时只能看到前 seq_len 长度的数据，而不是像LLM inference时可以看到之前的所有序列，是这样吗？

如果是的话，那在 test 时，如果出现了前面已有的序列长度小于 seq_len 的话，会怎么处理呢？

**Comment by WenWeiTHU** [comment]
是的。预测时可以看到seq_len长度，称为lookback窗口。因为数据集是按时间连续划分train/val/test的，在test时，第一个窗口时可以往validation set取lookback窗口的

**Comment by mawenju203** [comment]
> validation set取

如果使用新数据用于预测 pred，可以提供的序列长度不足seq_len，该如何操作呢？
例如： 训练的时候 seq_len 为 20， 但是我新数据总共才10条记录；是否是无法进行预测的；

难道模型提供的lookback窗口和预测的窗口大小都只能是固定的吗？

**Comment by mawenju203** [comment]
> 是的。预测时可以看到seq_len长度，称为lookback窗口。因为数据集是按时间连续划分train/val/test的，在test时，第一个窗口时可以往validation set取lookback窗口的


如果使用新数据用于预测 pred，可以提供的序列长度不足seq_len，该如何操作呢？
例如： 训练的时候 seq_len 为 20， 但是我新数据总共才10条记录；是否是无法进行预测的；

难道模型提供的lookback窗口和预测的窗口大小都只能是固定的吗？
