### ISSUE TITLE
How to deal with spatial information?

### ISSUE THREAD

**Issue by xiaoxiaokuye** [thuml/iTransformer#11]
I've observed that your model architecture is excellently designed to facilitate multi-agent interactions. However, it appears that current models are limited to handling scalar values. Could you elaborate on how your system can manage information based on XYZ coordinates?

**Comment by WenWeiTHU** [comment]
Since the current repo mainly focuses on the 2D temporal analysis. We will reopen this issue when we have a more specific answer to this task.

Related issues: https://github.com/thuml/iTransformer/issues/7.
