### ISSUE TITLE
GroundTruth 在實際值上做了什麽處理嗎？

### ISSUE THREAD

**Issue by Happleasei** [thuml/iTransformer#110]
例如：實際預測輸出的值大概在13左右，但是test_result裏面繪製出來的圖GroundTruth和pred都在-3，3之間。

**Comment by bigdata0** [comment]
肯定是z-score标准化了呗

**Comment by Happleasei** [comment]
好好好😂

| |
王海
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月09日 17:41 |
| 收件人 | thuml/iTransformer ***@***.***> |
| 抄送人 | HelloHai ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [thuml/iTransformer] GroundTruth 在實際值上做了什麽處理嗎？ (Issue #110) |

肯定是z-score标准化了呗
