### ISSUE TITLE
使用features 为MS进行模型的训练和预测，最后的preds = np.array(preds)，不是OT这一列的真实值吗？

### ISSUE THREAD

**Issue by mawenju203** [thuml/iTransformer#113]
作者您好!

问题有两个；

第一个是模型训练的时候会打乱数据顺序；这样我的训练数据应该如何组织呢？

1. 例如我要查看若干种商品一个月内的销售数量，我的'OT'应该是该商品每天的销售数量；

特征是 ：销售日期，商品编码，商品折扣，商品数量，商品今日销售数量？

这样如果训练的时候数据顺序被打乱，怎么学习时间和当天销售数量的关系呢？

第二个问题，使用训练的模型进行预测，预测的值感觉不是商品今日销售的数量呢？怎样转化为真实的销售数量呢？

**Comment by WenWeiTHU** [comment]
你好，训练的时候变量顺序不会被打乱

**Comment by WenWeiTHU** [comment]
Related issue: https://github.com/thuml/iTransformer/issues/116,

**Comment by mawenju203** [comment]
![image](https://github.com/user-attachments/assets/8cdd76ff-dad3-4ba4-9e87-74cf2b2963ac)
@WenWeiTHU  作者您好，但是这段代码的flag为 train的时候；shuffle_flag = True，不就是打乱数据吗？

**Comment by mawenju203** [comment]
> 您好，这个是在训练样本上进行打乱，而训练样本是数据集沿着时间维度上划分的窗口，变量之间是不会被打乱的

谢谢您，是我表述的错误；如果时间维度上打乱顺序，模型还是可以知道时间的顺序的吧；可以这样理解吗？
![image](https://github.com/user-attachments/assets/0abe25e4-1e95-4269-a0bd-c1727f5a1f6b)
这是我的数据；

我是按照天，预测三十天的OT结果；inverse在run.py中修改为True了；这样预测的应该就是OT这一列的结果了吗？

下面是脚本
![image](https://github.com/user-attachments/assets/ec3f6cdf-b796-4749-90ee-ee3e7b3cd4df)

**Comment by WenWeiTHU** [comment]
您好，请参考相关issue: https://github.com/thuml/iTransformer/issues/116

**Comment by mawenju203** [comment]
> 您好，请参考相关issue: #116

谢谢答复
