### ISSUE TITLE
请问时间步长在0.4-0.6之间不等该怎么调整代码。

### ISSUE THREAD

**Issue by Xxlx5649** [thuml/iTransformer#114]
![QQ截图20240830175044](https://github.com/user-attachments/assets/f890b3e7-df47-4064-a3d0-4a7183a1f047)

**Comment by WenWeiTHU** [comment]
你好，可以使用插值等方法进行预处理。模型默认输入是等间隔的，输入也会按相应的间隔输出，采样间隔差距不大的情况下可以任务模型以间隔平均值输出预测结果

**Comment by Xxlx5649** [comment]
非常感谢
