### ISSUE TITLE
关于预测数据处理的问题

### ISSUE THREAD

**Issue by Hejp5665** [thuml/iTransformer#117]
<img width="779" alt="image" src="https://github.com/user-attachments/assets/e28294d2-618e-4100-8737-a38a544df20d">
这里的标准化应该用训练数据作为基准进行标准化，不然会导致数据无法对齐，推理的结果产生偏差。

**Comment by WenWeiTHU** [comment]
您好，是的。建议不要单独使用这个数据加载器，详情请移步：https://github.com/thuml/Time-Series-Library

**Comment by Hejp5665** [comment]
我就是从https://github.com/thuml/Time-Series-Library 过来的，但它里面没有predict这个模块，感谢的回复。
