### ISSUE TITLE
I have a few questions regarding some parameters.

### ISSUE THREAD

**Issue by kujhin** [thuml/iTransformer#118]
These might be basic questions, but I'm not very experienced yet, so I apologize for any misunderstandings.

Features: If I set features to M, does that mean it's performing multivariate prediction without a specific target, predicting all variables? 

Moving_avg: How is the moving_avg parameter used?

Target_root_path vs. Root_path: What is the difference between target_root_path and root_path?

X-axis in the Output Graph: Why does the x-axis in the output graph have 196 units?

**Comment by bigdata0** [comment]
1.Yes. 
2.The parameter 'moving-avg' comes from the paper 'Autoformer'. As Autoformer was integrated into the Time series Library project, this parameter was added to integrate iTransformer into the TSLib project. In fact, this parameter has never been used in iTransformer.
3.
![image](https://github.com/user-attachments/assets/957b7f1b-55f2-4091-bc84-ced7f9f3f54e)
The root path is the directory where the dataset exists, and data_path is the file name.
4.I'm not sure what you're referring to. If you meant inputting 96 steps to predict the next 96 steps, the visualization should include the first 96 steps in the chart. You only need to focus on the fitting effect for the 96 steps starting from the 96th step.
