### ISSUE TITLE
关于预测的函数的理解

### ISSUE THREAD

**Issue by mawenju203** [thuml/iTransformer#119]
请问一下， 如果模型设置的是MS，预测的是OT， inverse = True;   pred_len = 30;
outputs = self.model(batch_x, batch_x_mark, dec_inp, batch_y_mark) ;这个函数是预测batch_x后面30个数据的OT值吗？还是预测的是什么呢？

**Comment by bigdata0** [comment]
是的

**Comment by mawenju203** [comment]
@bigdata0 谢谢您的回答
