### ISSUE TITLE
有关ETT等数据集的问题

### ISSUE THREAD

**Issue by bigdata0** [thuml/iTransformer#122]
作者您好，我对ETT等数据集存在一些疑问。
电变压器的油温不仅受内部负荷的因素影响，还与外部环境温度密切相关。气温作为不稳定的因素，有季节性模式存在，目前前人的工作大都引用过这个数据集，然而结果并不理想，我曾尝试过基于已有的工作进行非常简单的改写，删除大部分复杂的模块直接进行模型的训练，然而误差的结果居然比大多数已有的模型数据要更好，并且甚至接近sota，所以我认为大多数现有的工作无法捕获这种季节性的模式，iTransformer中利用隐式的位置信息并不需要位置编码，经过倒置后，只有几条固定特征的时间序列，它们各自独立嵌入不需要区分顺序，甚至有些数据集上的表现丢弃掉x_mark(data_stamp)后效果更好。对于ETT系列数据集的问题，希望作者您能够拨冗回复：
1.根据data_loader.py中所描述的内容，模型采用一年的ETTh1数据进行训练，4个月的数据进行验证，4个月的数据进行测试，如果设置为M多变量预测，那么油温是否能够仅根据外部负载情况以及输入的96步(96h，即前4天的负载和油温情况)，成功捕获到一年中气温变化与外部负载复杂的相互作用关系，最终得到油温以及外部负载情况的预测，又或者只是根据历史数据(前96步以及过去训练过程吃掉的数据学习到的模式)进行外部负载和油温历史趋势的保守生成(认为输入和预测部分的气温是稳定的，对历史数据进行“复制”)，使用该数据集是否存在一定问题。
2.对于目前大部分工作在ETT数据集上的结果可以被很简单的删除复杂模块的改动(作为一个baseline)超越，是否侧面说明了ETT数据集存在一定问题，又或者目前大部分的工作对于数据长期依赖的关系的相关设计存在问题？
3.weather数据集我在您的issues中也做过相关的回复，我认为这些数据集都有一定的问题，巧妇难为无米之炊，在这些数据集上不断调参想要获取更好的结果的各种设计并不利于技术真正的进步。
当然，以上内容也可能存在问题，希望作者您能够不吝赐教，想要知道您对于这些数据集的见解。

**Comment by WenWeiTHU** [comment]
感谢您的关注，我们也认为目前公认的benchmark存在一些问题：例如数据集长度过短的（普遍1-2年），部分变量不存在内生可预测性，导致模型无法学到有意义的时序转移，或仅依靠normalization和channel independence对数据过拟合。我们最近的工作基于ERA5提出了新的benchmark，覆盖40年多变量（4000k+）时序数据，后续我们计划开源出这个数据集，希望在这个领域见到更多有效的模型设计
