### ISSUE TITLE
脱离历史目标特征的信息

### ISSUE THREAD

**Issue by Dimitri666** [thuml/iTransformer#128]
作者您好，看了您的文章有所疑问。
我现在遇到一个场景，用9个时序特征来预测温度时序序列，模型不能直接把温度特征放入模型。
目前的多元时序预测模型都无法摆脱目标特征的历史信息， 我尝试过这些模型，发现其效果有限。
而在您的工作提到了Variate generalization似乎和我的场景比较类似。后面我尝试使用您的模型，将9个特征作为输入，预测最后时刻的温度序列，发现效果不是很好。
请问您觉得这个场景iTransformer适合吗？或者有什么其他方案。

**Comment by WenWeiTHU** [comment]
您好，可以参考一下我们最近的工作，能够支持带外生变量的时序预测：https://arxiv.org/abs/2402.19072

**Comment by WenWeiTHU** [comment]
merged in to this issue: https://github.com/thuml/iTransformer/issues/61
