### ISSUE TITLE
How to distinguish different tokens

### ISSUE THREAD

**Issue by jiqizaisikao** [thuml/iTransformer#13]
Hello, I would like to ask the original transformer to distinguish variables by adding position coding, so how does your method distinguish between different tokens?

**Comment by WenWeiTHU** [comment]
It is really a good question. Of course, the original transformer distinguishes **tokens** by adding position coding. However, the tokens of the original transformer represent different time steps. It is only true in our inverted version that tokens represent different variates.

**Comment by WenWeiTHU** [comment]
After understanding this, let us discuss the necessity of distinguishing the tokens. First, **distinguishing time steps is essential** because if the time points are permuted, it will lead to totally different predictions. So the original transformer must use the position embedding for attention to distinguish the **time points as tokens**. But in our inverted version, FFNs are applied to the time points. Since the order is already stored in the permutation of neurons of FFNs, the position embedding is no longer needed here.

**Comment by WenWeiTHU** [comment]
On the other hand, let us imagine if the variates are permuted, it is only necessary to satisfy the result of the output of variable X corresponding to the input of variable X. So **distinguishing variate is not essential but it is essential to keep them independent**. In fact, the original transformer does not distinguish them and even first mixes them into indistinguishable channels. In our model, we just keep them as independent tokens. They can also correlate with each other in the invert attention and finally come back to themselves.

**Comment by jiqizaisikao** [comment]
thank you for your reply,What happens if the variables are not independent of each other?

**Comment by WenWeiTHU** [comment]
At least, when originally independent variables are mixed into indistinguishable feature channels, it can be difficult to explicitly find out the correlations among variables, which is important for Multivariate Time Series Forecasting.

**Comment by jiqizaisikao** [comment]
The original transformer distinguishes different tokens by adding time embedding, but your algorithm does not have any way to distinguish different tokens. The time series itself is not a token. If the variables of different channels are not pre- tokenized with different MLPs, then In fact, it is equivalent to thinking that the time series itself is a different token, but in fact the time series itself is very similar and cannot be used directly as a token. MLP differentiates between times, but not between different variables

**Comment by jiqizaisikao** [comment]
In fact, you assume that the time series of different variables are themselves completely different, and the series itself can distinguish them

**Comment by WenWeiTHU** [comment]
Hi, we provide further clarification here. First of all, we will use two terms:

* Permutation-invariance
* Permutation-equivariance

For the details, please refer to the paper: https://arxiv.org/abs/1703.06114. There is also an intuitive blog for explain it: https://zhuanlan.zhihu.com/p/612736617

Notably, **Transformer without position embedding (termed Trm w/o PE) has both of the two properties**. For the temporal dimension of time series, permutation-invariance of Trm w/o PE leads to the lack of chronological awareness of time points. Therefore, position embedding should be introduced to solve this issue.

**Comment by WenWeiTHU** [comment]
However, for variate dimensions of time series, permutation-equivariance of Trm w/o PE is exactly what we want (note that permutation equivariant between variables means shuffling the input order of variables should not affect anything other than the output order of variables). 

More concisely, if token A belongs to variable 1 and does not belong to variable 2 and variable 3, we only care that V1 is different from V2/V3, but we are not concerned that V2 is different from V3 (if we do so, change the input order of V2 and V3 will cause additional effect to the output). That is why iTransformer does not use any position embedding on variate tokens.
