### ISSUE TITLE
关于归一化的问题

### ISSUE THREAD

**Issue by Bolin-Chen1** [thuml/iTransformer#130]
作者你好，我注意到代码是先划分的数据集，然后分别对训练、验证和测试集做的归一化。请问一下，这样的效果和先统一归一化再划分数据集区别大吗？

**Comment by wubizhi** [comment]
如果你先做归一化了，某种程度上来说应该是未来信息泄露了。因为，时间序列数据有很大的一个问题是drift，你怎么能够知道未来数据和历史数据可以用同一个normalization呢？用了统一归一化，效果会好，但是，从实际应用来说应该是不make sense。
