### ISSUE TITLE
data_factory中的参数设置问题

### ISSUE THREAD

**Issue by bigdata0** [thuml/iTransformer#134]
作者您好，此版本项目中的data_factory.py中测试集的batch_size设置为1，会显著降低模型每轮的测试速度。

**Comment by WenWeiTHU** [comment]
Please refer to: https://github.com/thuml/Autoformer/issues/104 and https://github.com/yuqinie98/PatchTST/issues/7

**Comment by bigdata0** [comment]
感谢您的回复。我会尝试在设置drop_last=False的前提下更改batch_size。
