### ISSUE TITLE
How iTransformer could training blazingly fast?

### ISSUE THREAD

**Issue by ikhsansdqq** [thuml/iTransformer#136]
Hi, thanks for sharing the iTransformer code earlier. I’ve made several adjustments to make it more flexible for my research. I’m curious, how is the iTransformer able to train so quickly with univariate time-series data? On average, it only takes around 20 epochs and less than 10 seconds of training time. Could you explain how that's possible?

I used `iTransformer` external libraries from [`@lucidrains`](https://github.com/lucidrains/iTransformer)

Please take a look at my epoch training size, I've set the maximum epochs of 500.

![image](https://github.com/user-attachments/assets/acf78a5c-ae1e-479e-af42-d4f0d6ab6cc4)

**Comment by WenWeiTHU** [comment]
For univariate time series, the token number is one.
