### ISSUE TITLE
请教 w/o variate attention 消融实验是怎么做的？

### ISSUE THREAD

**Issue by wayhoww** [thuml/iTransformer#138]
我尝试将 attention mask 设置成下面的样子，来消除 variate attention. 数据集是 traffic

```txt
0 - - - 0 0 0 0
- 0 - - 0 0 0 0
- - 0 - 0 0 0 0
- - - 0 0 0 0 0
- - - - 0 0 0 0
- - - - 0 0 0 0
- - - - 0 0 0 0
- - - - 0 0 0 0
```

其中 `-` 表示 `-inf`，发现加了上面的 attention mask 并不影响 iTransformer 的 mse。

请问这个消融实验的正确做法是什么呢？如果能提供正确做法或指出我的做法的问题，万分感谢🙏

**Comment by WenWeiTHU** [comment]
Hi, you can remove the attention layer, leaving the FFNs only.

**Comment by wayhoww** [comment]
Thanks @WenWeiTHU for providing the details!
