### ISSUE TITLE
decomp function

### ISSUE THREAD

**Issue by gkyustc** [thuml/iTransformer#14]
Hi ,

May I ask where the _decomp_ function is from
(https://github.com/thuml/iTransformer/blob/52fad3f9ed16da18f51605545d3571b551771310/model/iTransformer.py#L42)

Regards

**Comment by WenWeiTHU** [comment]
Sorry, it was a redundant code. We have fix it in https://github.com/thuml/iTransformer/commit/b82e2042dd6bf94688d92113ff8f4a75a820dfca
