### ISSUE TITLE
您好，请问啥时候开源TimeXer

### ISSUE THREAD

**Issue by aligaduocaisang** [thuml/iTransformer#140]

**Comment by aligaduocaisang** [comment]
您好，timeenc为0的时候，出现下面这种情况
![Uploading image.png…]()

**Comment by aligaduocaisang** [comment]
您好，当timeenc=0时，出现下面这种情况，
data_stamp = df_stamp.drop(['date'], 1).values
TypeError: drop() takes from 1 to 2 positional arguments but 3 were given
是否可以修改为data_stamp = df_stamp.drop(['date'], axis=1).values

**Comment by WenWeiTHU** [comment]
您好，TimeXer将在这个仓库开源：https://github.com/thuml/TimeXer
