### ISSUE TITLE
Clarification on Self-Supervised Learning and Fine-Tuning in PatchTST Implementation

### ISSUE THREAD

**Issue by mosszhd** [thuml/iTransformer#141]
Hi, First of all thanks a lot for sharing the code. 

I reviewed the code for PatchTST in the Time-Series-Library. In the original implementation of PatchTST, they use both self-supervised and supervised learning. Could you confirm if you applied any self-supervised learning when training PatchTST in your setup? Additionally, did you implement any fine-tuning methods? 

Original PatchTST implementation: https://github.com/PatchTST/PatchTST/tree/main/PatchTST_supervised
TIme series library implementation of PatchTST: https://github.com/thuml/Time-Series-Library/blob/main/models/PatchTST.py

**Comment by WenWeiTHU** [comment]
Thanks for your question. We do not implement any self-supervised learning and fine-tuning process in our setup.

**Comment by WenWeiTHU** [comment]
If you are interested in the setup of self-supervised learning in time series, we recommend the two codebases for you :)
* https://github.com/thuml/SimMTM
* https://github.com/thuml/TimeSiam

**Comment by mosszhd** [comment]
Thanks a lot.
