### ISSUE TITLE
论文中table10结果

### ISSUE THREAD

**Issue by xkpengl** [thuml/iTransformer#142]
我用您的代码，最好的结果是multivariate_forecasting，其中traffic跑出的结果（在历史窗口和预测窗口都为96的情况下）MSE：0.4173510670661926，MAE：0.28778335452079773，与您论文中的结果似乎还是有差距
![image](https://github.com/user-attachments/assets/313c92af-3166-4061-bf03-7919deeb12ab)

**Comment by WenWeiTHU** [comment]
Hi, thanks for your usage! According to the provided codebase and script, the reproduced result will be better than those reported in our paper: 

<img width="975" alt="image" src="https://github.com/user-attachments/assets/e5d28e15-1f69-4498-be4c-35864e91799b">

I think one potential question is the experimental environment. Please try this configuration: PYTORCH2.0.0 CUDA11.2

If you have further questions, please refer to the checkpoint we provide here: https://cloud.tsinghua.edu.cn/f/dd6ec819d91c4c9889b8/?dl=1
