### ISSUE TITLE
同一张卡多次复现itransformer结果没有任何变化

### ISSUE THREAD

**Issue by 9394-lab** [thuml/iTransformer#146]
大佬您好，我多次用一张卡复现itransformer，为什么多轮跑出的结果完全一致，以我的理解用 random seeds去跑预测值应该稳定的在一个范围内波动，而不是完全一致。在这个pipeline里，跑其他模型则不会出现预测结果完全一致的情况。

下面是我复现的结果：（是不是默认的itransformer用了什么save机制我没有发现？，或者其他什么原因导致的。）PS：03上复现不出论文里的结果

PEMS03_96_12_run1_iTransformer_PEMS_M_ft96_sl0_ll12_pl512_dm4_nh4_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_enable_intra_1_enable_inter_1  
mse:0.07475799322128296, mae:0.1816963106393814

PEMS03_96_12_run2_iTransformer_PEMS_M_ft96_sl0_ll12_pl512_dm4_nh4_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_enable_intra_1_enable_inter_1  
mse:0.07475799322128296, mae:0.1816963106393814

PEMS03_96_12_run3_iTransformer_PEMS_M_ft96_sl0_ll12_pl512_dm4_nh4_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_enable_intra_1_enable_inter_1  
mse:0.07475799322128296, mae:0.1816963106393814

**Comment by WenWeiTHU** [comment]
您好，用固定的seed跑实验效果应该是不变的
