### ISSUE TITLE
Reversible Instance Normalization Verification

### ISSUE THREAD

**Issue by ikhsansdqq** [thuml/iTransformer#147]
Dear @wuhaixu2016, I noticed that in Lucidrain's pip package, the iTransformer came with reversible instance normalization. However, using Revin or not, did not contribute anything during my experiment. Have you verified the RevIN function in the lucidrain's repository?

Thanks.

**Comment by WenWeiTHU** [comment]
Hi, RevIN is intended to resolve the distributional shift of prediction windows (non-stationary). It is a non-essential module for some applications.
