### ISSUE TITLE
Can iTransformers be used as a Large Language Model architecture?

### ISSUE THREAD

**Issue by JasonS05** [thuml/iTransformer#17]
Have you done any research on the performance per parameter of iTransformers for language tasks? If the gains shown in the graph transfer over well to natural language tasks, this could be extremely valuable for LLMs. If you haven't done any research on that specifically, can you tell me in what ways it could reasonably be projected to behave differently? For example, would context still work the same way? Could a model trained on a fixed context length also be able to scale well to a larger context length without hacks like RoPE scaling?

**Comment by WenWeiTHU** [comment]
Wow, that is a fascinating question. In fact, we have not tried out iTransformer on language tasks. Can you elaborate more on the "graph transfer" and provide more details about the specific language tasks?

**Comment by JasonS05** [comment]
You showed this graph which demonstrates consistent performance gains over a variety of tasks:

![Radar graph](https://raw.githubusercontent.com/thuml/iTransformer/main/figures/radar.png)

I'm wondering if these gains also apply to language tasks.

LLMs are usually trained to extend a truncated piece of textual data. Once trained, they are often finetuned on a second dataset to optimize the model for any of a number of potential tasks. The most common task is a typical chat/instruction type situation, where a user inputs prompts and the LLM responds. This is the way that ChatGPT works. In the open source world, the way this is implemented is typically by giving the LLM something like this:
```
### System:
The following is a transcript of a conversation between a user and a helpful AI chatbot designed to assist the user with whatever they ask.

### User:
Hello. Tell me about yourself.

### AI:

```
And then the LLM proceeds to complete this incomplete transcript with what it thinks a "helpful AI chatbot" would say, and the output of the LLM is given back to the user. The system prompt is typically hidden from the user. The strings `### User:` and `### AI:` are also typically hidden from the user and instead replaced with whatever formatting the application uses to distinguish the user and AI. In the case of ChatGPT, these strings are not even strings at all but instead represented with special tokens that have no textual equivalent.

**Comment by WenWeiTHU** [comment]
Thank u very much for your sharing! 

It can be quite beneficial to embrace the advanced structural design of these LLMS, such as RoPE and pre-Norm. We will continue to trial these technologies.
