### ISSUE TITLE
bash ./scripts/multivariate_forecast/Traffic/iTransformer.sh

### ISSUE THREAD

**Issue by MInYangP-OU** [thuml/iTransformer#18]
File "/home/featurize/iTransformer/run.py", line 79
    help='experiemnt name, options:['MTSF', 'partial_train']')  

SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by WenWeiTHU** [comment]
Thank you very much, we have fixed it in https://github.com/thuml/iTransformer/commit/14d1dc5a030be7aafdee8d9df9b9ab2abddc435e.
