### ISSUE TITLE
关于数据集OT列的疑惑

### ISSUE THREAD

**Issue by Nickel-Nie** [thuml/iTransformer#19]
您好，想请问一下csv文件中的OT列含义是什么？是作为多输入单输出的一个目标值吗？

**Comment by WenWeiTHU** [comment]
您好，是的。设置args.feature='MS'模式时会把除了OT之外的列当做协变量，进行多对一预测。

相关issue: https://github.com/thuml/Autoformer/issues/97

**Comment by yyMTS** [comment]
您好 我看您的源代码里面给出的标志位全部为M，M应该为多变量预测多变量，但target又为OT。我想问，这样设置与标志位设为MS，target为OT有什么区别呢？

**Comment by WenWeiTHU** [comment]
> 您好 我看您的源代码里面给出的标志位全部为M，M应该为多变量预测多变量，但target又为OT。我想问，这样设置与标志位设为MS，target为OT有什么区别呢？

设置为M时，target参数无效
