### ISSUE TITLE
除OT列的其他变量预测

### ISSUE THREAD

**Issue by yyMTS** [thuml/iTransformer#20]
您好 请问我想预测数据集中除OT之外的变量 更改完目标变量target之后训练预测 训练结果的MSE 和MAE与OT是一模一样的 这是正确的吗？

**Comment by WenWeiTHU** [comment]
您好，由于代码实现问题，目标变量默认为csv最后一列，修改target参数暂时不起作用

**Comment by yyMTS** [comment]
您好 非常感谢您的回复 单变量预测应该是（args.features='S'） 
我如果修改 
                f_dim = -1 if self.args.features == 'MS' else 0
                outputs = outputs[:, -self.args.pred_len:, f_dim:]
                batch_y = batch_y[:, -self.args.pred_len:, f_dim:].to(self.device)
这几行代码 是不是就可以进行其他变量的预测

**Comment by WenWeiTHU** [comment]
您好，可以的
