### ISSUE TITLE
A basic question: can we have data provider for time series with time column not in dd/mm/yy formate?

### ISSUE THREAD

**Issue by jianzuo** [thuml/iTransformer#22]
Hi,
I came from battery background, usually, the dataset we use for prediction is hourly collected, i.e., 
the time column is 0, 1, 2, 3, 4, ..., for example. And the task is to predict battery voltage degradation
and remaining lifetime.

For this kind of dataset, can we **have a convenient data provider** to run the model?
Thank you in advance for checking this!

**Comment by WenWeiTHU** [comment]
Hello, you cen refer to the README for using customized dataset: https://github.com/thuml/iTransformer/tree/main/scripts/multivariate_forecast

**Comment by jianzuo** [comment]
@WenWeiTHU Thank you very much for the quick response and sharing.
Going to check those resources,

**Comment by WenWeiTHU** [comment]
Yeah, of course you can use this time column! In fact, the timestamps are regard as an extra variate token in our model (as the model input but not to predict it). You can try out your customize feature embedding of covariates.

**Comment by jianzuo** [comment]
The custom dataset class works on my dataset. I am going to further explore the modeling training and prediction to improve the prediction accuracy. 
Thanks!

**Comment by cotucotudu** [comment]
> Hello, you cen refer to the README for using customized dataset: https://github.com/thuml/iTransformer/tree/main/scripts/multivariate_forecast

404 - page not found

**Comment by WenWeiTHU** [comment]
> > Hello, you cen refer to the README for using customized dataset: https://github.com/thuml/iTransformer/tree/main/scripts/multivariate_forecast
> 
> 404 - page not found

Sorry, the file structure has been updated. Please use this one: https://github.com/thuml/iTransformer/tree/main/scripts/multivariate_forecasting
