### ISSUE TITLE
Can you write a tutorial on how to use ITransformer to run custom datasets？

### ISSUE THREAD

**Issue by liujian123223** [thuml/iTransformer#23]
Your work is very beautiful. Running the dataset corresponding to the DEMO you provided is very simple, but I don't know how to run a custom dataset (such as household energy consumption data, where each sample has only one variable, which is the overall energy consumption value). I hope you can provide a tutorial. Thank you！

**Comment by WenWeiTHU** [comment]
Hello, a related issue https://github.com/thuml/iTransformer/issues/22. You may have a discussion on this!
