### ISSUE TITLE
PEMS dataset

### ISSUE THREAD

**Issue by Xyhi** [thuml/iTransformer#24]
I notice that PEMS datasets include 4 parts: `PEMS03, PEMS04, PEMS07, PEMS08`. Could you please tell me which dataset was used in the original paper's experiment? Thanks!

**Comment by WenWeiTHU** [comment]
Hello, the scripts are for PEMS03 currently. The complete script will be uploaded in one week, since we have revised our paper with supplementary results from all the subsets!
