### ISSUE TITLE
Can`t load a custom dataset

### ISSUE THREAD

**Issue by TradeForce-AI** [thuml/iTransformer#28]
Hello guys, thanks for this amazing work.. 
i am having some issue loading a custom dataset, the parameters are this:
`python -u run.py \
  --is_training 1 \
  --root_path ./dataset/earth/ \
  --data_path es.csv \
  --model_id es_96_96 \
  --model $model_name \
  --data custom \
  --features MS \
  --seq_len 5 \
  --pred_len 1 \
  --e_layers 2 \
  --enc_in 6 \
  --dec_in 6 \
  --c_out 1 \
  --des 'Exp' \
  --d_model 512\
  --d_ff 512\
  --itr 1\
  --freq d\
  --target_root_path ./dataset/earth/ \
  --target_data_path 'es.csv'`

the dataset look like this:
`date,0,1,2,3,4,OT

2001-01-02,1320.280029296875,1320.280029296875,1276.050048828125,1283.27001953125,1129400000,1347.56005859375
2001-01-03,1283.27001953125,1347.760009765625,1274.6199951171875,1347.56005859375,1880700000,1333.3399658203125`

but i am keep getting:
**RuntimeError: Trying to resize storage that is not resizable**
Any idea what am i doing wrong?

**Comment by WenWeiTHU** [comment]
Hello, could you elaborate more on the custom dataset? Does it also happen in our provided datasets?
