### ISSUE TITLE
基础配置问题

### ISSUE THREAD

**Issue by Sunlandis** [thuml/iTransformer#29]
作者您好！
1.在requirement中，sklearn包这样表述我拉到colab里运行是下载不了这个包的，我在服务器上手动改为了scikit-learn的写法成功加载了，希望作者能在requirement中修正。
2.希望提供适配此开源代码的pytorch、CUDA以及cuDNN的版本号，以便于复现者更快部署本地环境，感谢！

**Comment by ZDandsomSP** [comment]
您好，感谢您的反馈，我们已经在最新的提交中更新相关的版本信息。
