### ISSUE TITLE
怎么确定最优的输入长度（seq_len）

### ISSUE THREAD

**Issue by LY-must-win** [thuml/iTransformer#3]
我在预测electricity.csv文件下的数据时得到了较好的预测效果，但用自己的气象数据集进行预测时，图像的拟合结果较差。用何种方法可以确定最优的输入长度呢？需不需要调整其他参数？
![image](https://github.com/thuml/iTransformer/assets/103368413/e0477808-0447-4be1-89ec-fe3d925c60a6)

**Comment by LY-must-win** [comment]
tip:数据分辨率为10min的非平稳数据

**Comment by WenWeiTHU** [comment]
我认为这属于特征工程的部分，需要结合具体的场景来看。大数情况下需要先确定一个固定的输入长度（例如气象预报中一般会先根据预报员的经验，确定使用过去一周的某些气象指标，来预测未来24h的降雨量）再进行模型选择。更长或者更短的模型输入都不一定会带来更好的效果。换句话说，模型输入长度是需要根据领域先验知识以及场景下数据的可获得性确定的。训练模型之前，模型默认提供的输入包含足够的且不太冗余的历史信息，可以进行合理的预测，如果相关机理知识或者经验较少，可以尝试[optuna](https://optuna.readthedocs.io/zh-cn/latest/index.html#)/[nni](https://nni.readthedocs.io/zh/stable/index.html)等超参数调优框架。

**Comment by LY-must-win** [comment]
> 我认为这属于特征工程的部分，需要结合具体的场景来看。大数情况下需要先确定一个固定的输入长度（例如气象预报中一般会先根据预报员的经验，确定使用过去一周的某些气象指标，来预测未来24h的降雨量）再进行模型选择。更长或者更短的模型输入都不一定会带来更好的效果。换句话说，模型输入长度是需要根据领域先验知识以及场景下数据的可获得性确定的。训练模型之前，模型默认提供的输入包含足够的且不太冗余的历史信息，可以进行合理的预测，如果相关机理知识或者经验较少，可以尝试[optuna](https://optuna.readthedocs.io/zh-cn/latest/index.html#)/[nni](https://nni.readthedocs.io/zh/stable/index.html)等超参数调优框架。

非常感谢您的解答，谢谢！
