### ISSUE TITLE
forecasting 中的inverse 问题

### ISSUE THREAD

**Issue by tears743** [thuml/iTransformer#31]
Test过程中，如果设置了inverse为True，执行到下面的代码时
```
if test_data.scale and self.args.inverse:
                    outputs = test_data.inverse_transform(outputs)
```
会报错：ValueError: Found array with dim 3. None expected <= 2.
原因是使用的sklearn中的StandardScaler只能接受2维数组导致，大佬空了改一下吧。

**Comment by WenWeiTHU** [comment]
Thanks! Fixed in https://github.com/thuml/iTransformer/commit/133e07f5e8176d4da6873dd4f835762eb4160f54.
