### ISSUE TITLE
Questions about how to improve model training speed

### ISSUE THREAD

**Issue by Davidtssssss** [thuml/iTransformer#32]
Hello dear author, thank you very much for the work you shared, it is really fascinating. After reading the article and source code, we have some questions and are looking forward to your guidance.
Q1: When our GPU performance is insufficient, can we use FP16 or AMP to improve the training speed of the model without affecting the model performance?
Q2: When we tried to run the "bash ./scripts/multivariate_forecasting/Traffic/iTransformer.sh" script, we found that the training time takes about 2-3 days. Is this normal? We are using a single v100-16GB. What methods can we try to improve the training speed of the model? For example, using multiple GPUs, such as using 4 P100s? Or switch to a GPU with higher computing power, such as 4090, 4080 or 3090?
Q3: If we plan to run this model on a machine with more computing power, what should we pay more priority to? For example, is it the single-core performance of the CPU, the main frequency, or the number of cores in the CPU? GPU memory bit width and bandwidth? Does PCIE3.0 or 4.0 have a big impact when connecting the GPU to the motherboard?
I'm very sorry for asking so many questions, and I apologize again for wasting your time and energy! We look forward to your answers and guidance, and wish you better top-level conference results!

**Comment by ZDandsomSP** [comment]
Hello, thank you for your feedback:
Regarding the first question: Our model indeed has the ability to improve training speed without significantly affecting performance. Please read our paper Figure 5 and its experimental explanation section for a more detailed explanation.
The second question: The training time you described far exceeds the training time for the Traffic dataset in our paper. Our model speed should not require multiple GPU training to reach a considerable speed (compared to models such as PatchTST that use CI). Please check if your system environment supports CUDA and normal GPU training, and if there are any issues with your GPU device.
The third issue: GPU memory bit width may need to be prioritized, and CPU performance requirements may only be related to dataset size.
We are not professional machine learning engineers, the above suggestions are for reference only. Thank you again for your feedback!

**Comment by Davidtssssss** [comment]
Thank you very much for your guidance! We will take a closer look at the environment configuration. I wish you better paper output! Thank you again for taking the time to reply, thank you very much! :)

**Comment by syrGitHub** [comment]
@Davidtssssss Hi, I have the same problem as Q2. Did you take care of it?
![image](https://github.com/thuml/iTransformer/assets/31035074/9be70555-2ef8-40b0-8eae-f592dd10cc0b)
vs
![image](https://github.com/thuml/iTransformer/assets/31035074/95f81d1d-421d-420c-a399-23d95c4145df)

**Comment by syrGitHub** [comment]
@Davidtssssss Hi, I have the same problem as Q2. Did you take care of it?
![image](https://github.com/thuml/iTransformer/assets/31035074/0f1d2659-ee56-4f7f-a958-51331cec7760)
vs
![1714653261553](https://github.com/thuml/iTransformer/assets/31035074/fe0c57d8-4ec9-4f69-a83f-b99c20902c09)
