### ISSUE TITLE
Univariate forecast with exogenous variables 

### ISSUE THREAD

**Issue by kailu22** [thuml/iTransformer#34]
Hi there, thanks for the excellent work. I wonder if the model is able to perform univariate forecasting with exogenous variables. It seems no to me at first glance. Any insights would be appreciated.

**Comment by WenWeiTHU** [comment]
Hello, it can be accomplished by using both of the target variate and exogenous variables as inputs to the model (since they can correlate with each other inside the trm blocks), but end up taking only the target variable. Related issue: https://github.com/thuml/iTransformer/issues/4
