### ISSUE TITLE
traffic数据集问题

### ISSUE THREAD

**Issue by Sunlandis** [thuml/iTransformer#37]
我的研究涉及现实物理意义解释。在itransformer提供的谷歌云端的数据集中，traffic这个数据有17545个时间步记录，862个变量，其中第一个date记录时间戳，860个变量 是否是记录的旧金山860个高速路监测点的流量数据呢？另外，最后一个变量OT我不知道其物理意义，暂时理解应该不是总占有率或者平均占有率，因为这可以通过前面860个变量简单加权计算得出，不需要这么复杂的模型预测，想请问能否提供OT的出处的解释。
另外这份traffic数据网上的各自介绍都说是基于2015-2016年的旧金山高速路数据，但是数据内记录却是2016.7-2018.7这两年间的数据，与[PEMS]任何一个子集也对应不上，在paperswithcode上也查不到资料，不知可否给出具体对数据集解释的官方网址？因为这也是许多顶会用过的应该有出处，谢谢！

**Comment by WenWeiTHU** [comment]
https://github.com/laiguokun/multivariate-time-series-data

**Comment by farazBhatti** [comment]
@WenWeiTHU  Hi, Ive gone through the above link, but i couldnt find anything useful on 'OT', can you please guide? I am trying to use sensor data for forecasting for that i need to know how previous data works.
Thanks
