### ISSUE TITLE
参数设置

### ISSUE THREAD

**Issue by 1995657** [thuml/iTransformer#38]
请问ETTh1的具体训练参数是多少，我按照代码中参数的设置，并不能得到论文中的精度。

**Comment by ZDandsomSP** [comment]
<img width="405" alt="image" src="https://github.com/thuml/iTransformer/assets/88132465/f3a6108a-5ed5-4423-a53e-cec725b4bc40">
您好，我们在我们的实验环境中进行了确认，结果与论文中的一致，请您检查一下您的代码是否正确，以及环境是否符合我们提供的requirements（这有时会影响实验结果）。

**Comment by 1995657** [comment]
感谢您的回信，谢谢。我会按照您给的参数再去试一试。祝您元旦快乐，虽然是迟到的祝福。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/iTransformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月1日(星期一) 中午12:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/iTransformer] 参数设置 (Issue #38)





 image.png (view on web) 您好，我们在我们的实验环境中进行了确认，结果与论文中的一致，请您检查一下您的代码是否正确，以及环境是否符合我们提供的requirements（这有时会影响实验结果）。

**Comment by 1995657** [comment]
你可以把完整的参数设置截图发一下吗？这边调参的结果还并不是很好

**Comment by WenWeiTHU** [comment]
即为提供的scripts的参数设置
