### ISSUE TITLE
What change should be done for good if X and Y have different num_variates?

### ISSUE THREAD

**Issue by xtzd** [thuml/iTransformer#4]
I see that the examples given are all with the same dimension of input features and output features, I would like to ask what kind of modification should be done to the model if the input features are more than one and the output features are 1 or different, what kind of modification should be done to the model to make it better in this case? For example, adding a layer of full connection layer at the end, is this simple approach a good choice?

**Comment by WenWeiTHU** [comment]
Yeah, I think you mean the forecasting scenario with covariant variates (only part of the input variates are concerned).In our model, it is more reasonable to utilize the **cross-attention** which communicates the input variates (as tokens) with the target variates and solely outputs the latter.  We are still trying it out!
