### ISSUE TITLE
Export model to ONNX

### ISSUE THREAD

**Issue by Temppus** [thuml/iTransformer#42]
Hi, great open source implementation.
I am very new to ML ecosystem and I am trying to export trained itransformer model to ONNX, but currently failing to do so.
Do you think it would be possible to include sample or guide me how to do it ?
Thank you.

**Comment by Temppus** [comment]
Nevermind it seems like I managed to export is successfully

**Comment by WenWeiTHU** [comment]
That sounds good! We will appreciate it greatly if you get involved in this repo and pr this part.
