### ISSUE TITLE
Regarding the figures in the article

### ISSUE THREAD

**Issue by camallia1** [thuml/iTransformer#44]
![0a44f215308c893ddd6ebc228675cd1]
Hello, I am a beginner. May I ask how the heat map about attention mechanism in the article is drawn, and how can I create variables for drawing images?Could you please give me an example？

**Comment by WenWeiTHU** [comment]
It is the attention scores from the trained model by passing an input multivariate series and then visualized, which is formulated as follows:

<img width="200" alt="图片" src="https://github.com/thuml/iTransformer/assets/39073236/bd745f48-ec2a-4bb1-b11c-96d6064908ae">

**Comment by camallia1** [comment]
Thank you for your answer. How should I call the A matrix in FullAttention? Could you give me a code example

**Comment by WenWeiTHU** [comment]
https://github.com/thuml/iTransformer/blob/main/layers/SelfAttention_Family.py#L147
