### ISSUE TITLE
StandardScaler vs iTransformer normalization

### ISSUE THREAD

**Issue by Temppus** [thuml/iTransformer#46]
Hi,I am playing with custom dataset and exploring different parameters.

I noticed that custom dataset loader uses [StandardScaler ](https://github.com/thuml/iTransformer/blob/ce2ae5b414a764d4801abf28b5913806af61063d/data_provider/data_loader.py#L221C7-L221C7) by default. However iTransformer also supports [normalization ](https://github.com/thuml/iTransformer/blob/ce2ae5b414a764d4801abf28b5913806af61063d/model/iTransformer.py#L43)that uses normalization formula that is same as StandardScaler uses ?

1. Are these two doing same thing (over same data) ?
2. If yes this means that I should be using `--use_norm 0` ?

Thank you for response.

**Comment by WenWeiTHU** [comment]
Hello, see this for the detailed discussion: https://github.com/thuml/Nonstationary_Transformers/issues/9.
