### ISSUE TITLE
Dimension issue for backtesting

### ISSUE THREAD

**Issue by Dongzhikang** [thuml/iTransformer#48]
Hi! I really appreciate your great work! 

I am using it to test on my custom data. I have changed Dataset_Custom class in data_loader.py. However, I have a question about the role of seq_len, pred_len and label_len. Can you please explain it? 

And I want to train the model in a sliding window way, say train on data[i:i + window_size] and test on data[i + window_size + 1]. How can I set my seq_len, pred_len and label_len? Thank you very much!

**Comment by WenWeiTHU** [comment]
Hello, please refer this: https://github.com/thuml/Time-Series-Library/issues/49
