### ISSUE TITLE
Why does the time scale affect prediction accuracy?

### ISSUE THREAD

**Issue by wangchz13** [thuml/iTransformer#5]
Hello,thanks for this excellent work!
I used iTransformer to train on my own data set (univariate,no 'date'column),and the results were much better when the dataset was spaced 1 second apart than 1 hour,what could be the reason?Here is a comparison of the results:
1s:mse:0.05796017870306969,mae:0.1638924479484558
1h:mse:0.4430641829967499,mae:0.46550384163856506
Thanks again.

**Comment by WenWeiTHU** [comment]
Oh, that is very interesting. Could it be that the data obtained at different sampling intervals have different normalization ranges, or that the number of predicted points changes? Could you please provide some more detailed information, such as the prediction visualization of the same period under the two settings?

**Comment by wangchz13** [comment]
@WenWeiTHU 
Hello, in both Settings, the sequence data is the same, only the time interval is different, like this:
1S:
date                OT
2016-07-01 00:00:00 1.11
2016-07-01 00:00:01 2.22
2016-07-01 00:00:02 3.33
1H:
date                OT
2016-07-01 00:00:00 1.11
2016-07-01 01:00:00 2.22
2016-07-01 02:00:00 3.33
and the seq_len, pred_len are all the same.

**Comment by WenWeiTHU** [comment]
Okay, that is unexpected. We will try it out soon.

**Comment by wangchz13** [comment]
Thanks.

**Comment by ZDandsomSP** [comment]
We've test our framework on dataset with manually changed timestamp density, and the results show no clear differences. Please check if your usage method and code implementation are correct.
<img width="525" alt="89ebdb0c69a942ed11c9a7b2260b16d" 
<img width="527" alt="f022edd9c4ddb4536334f797674a761" src="https://github.com/thuml/iTransformer/assets/88132465/608c4ea7-4a5a-4e4f-b4b3-1e236e90cf42">
src="https://github.com/thuml/iTransformer/assets/88132465/eb32d291-0b51-4228-a57d-53f11da2657a">
<img width="425" alt="831ded7f4b4ba11e392a7809d6a3416" src="https://github.com/thuml/iTransformer/assets/88132465/408e67c2-9682-4648-a376-181be91bd95c">
