### ISSUE TITLE
关于输入数据的标准化处理

### ISSUE THREAD

**Issue by aistream69** [thuml/iTransformer#51]
官方例程中，self.scale和self.use_norm默认都是开启的，这样在data_loader.py中读取数据时会调用一次self.scaler.transform做数据标准化处理，之后在iTransformer.py的forecast中还会再做一次Normalization，请问是否重复了呢，还是说有其他考量？谢谢

**Comment by WenWeiTHU** [comment]
https://github.com/thuml/iTransformer/issues/46
