### ISSUE TITLE
预测结果很差？

### ISSUE THREAD

**Issue by kerry999** [thuml/iTransformer#52]
你好，

我用命令bash ./scripts/multivariate_forecasting/Traffic/iTransformer.sh，结果很差，只有周期（这个直接FFT就行，不需要ai），没有其他信息。
<img width="781" alt="截屏2024-01-30 11 59 50" src="https://github.com/thuml/iTransformer/assets/16098024/1450cdab-a68a-48d4-9a78-2b8c204c983b">
[3140.pdf](https://github.com/thuml/iTransformer/files/14092595/3140.pdf)

excahnge的结果也很差：
<img width="753" alt="截屏2024-01-30 11 50 52" src="https://github.com/thuml/iTransformer/assets/16098024/5b380d2a-9d32-4627-b6b4-74fd9359c2f0">
[780.pdf](https://github.com/thuml/iTransformer/files/14092600/780.pdf)

我在Mac mini M2上运行的算法。对脚本做了少量改动，把cuda换成了mps。类似这样：
if torch.backends.mps.is_available():
    device = torch.device("mps")

什么地方能看到你们官方的test_results目录的内容吗？

**Comment by kerry999** [comment]
附：脚本正常运行结束，没有报错
[run_exchange.log](https://github.com/thuml/iTransformer/files/14092619/run_exchange.log)

**Comment by WenWeiTHU** [comment]
您好，请尝试使用cuda环境和原始脚本复现结果

**Comment by aiot-tech** [comment]
met the same thing like this when running the oringinal scirpt

**Comment by aiot-tech** [comment]
can you the author provide the result that you ran with the exchange dataset?

**Comment by ZDandsomSP** [comment]
![image](https://github.com/thuml/iTransformer/assets/88132465/e88d6f28-a86b-4c09-aeb2-4f719407ad14)

Hello, we have repeated the experiment of exchange dataset script on our platform and the results are consistent with the paper.

Please confirm that your experimental environment (including Python and Torch versions) is consistent with the requirements we provide. If necessary, please contact us to provide ckpt

**Comment by aiot-tech** [comment]
```
Updating learning rate to 3.90625e-07
	iters: 100, epoch: 10 | loss: 0.1565858
	speed: 0.1291s/iter; left time: 7.8743s
Epoch: 10 cost time: 3.715930461883545
Epoch: 10, Steps: 160 | Train Loss: 0.1216311 Vali Loss: 0.1234729 Test Loss: 0.0862727
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : Exchange_96_96_iTransformer_custom_M_ft96_sl48_ll96_pl128_dm8_nh2_el1_dl128_df1_fctimeF_ebTrue_dtExp_projection_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 1422
test shape: (1422, 1, 96, 8) (1422, 1, 96, 8)
test shape: (1422, 96, 8) (1422, 96, 8)
mse:0.08620689809322357, mae:0.20608624815940857
```
I got the same results as you provided above, but the predictions I got on the testset were very bad. The entire prediction curve resembled a straight line and seemed to be fitting the mean of the true values ​​without being able to predict accurately. What are your results on the testset? Can you provide this part of the results, such as prediction charts?

**Comment by aiot-tech** [comment]
> 你好，
> 
> 我用命令bash ./scripts/multivariate_forecasting/Traffic/iTransformer.sh，结果很差，只有周期（这个直接FFT就行，不需要ai），没有其他信息。 <img alt="截屏2024-01-30 11 59 50" width="781" src="https://private-user-images.githubusercontent.com/16098024/300675267-1450cdab-a68a-48d4-9a78-2b8c204c983b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDk3NDQsIm5iZiI6MTcxMDc0OTQ0NCwicGF0aCI6Ii8xNjA5ODAyNC8zMDA2NzUyNjctMTQ1MGNkYWItYTY4YS00OGQ0LTlhNzgtMmI4YzIwNGM5ODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA4MTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwOWViZGU0MWFiNDg0ODJlNmM5MzYzMjg0Mzg0N2Y1ZTM4NTVkOTlkMGQwYzgxY2QxOGY4N2VjODQ0YTRmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.anHLn7sV-W-ZwoKYfkTwBJNcjoo4EDPYW6d1uL3Ilyo"> [3140.pdf](https://github.com/thuml/iTransformer/files/14092595/3140.pdf)
> 
> excahnge的结果也很差： <img alt="截屏2024-01-30 11 50 52" width="753" src="https://private-user-images.githubusercontent.com/16098024/300675317-5b380d2a-9d32-4627-b6b4-74fd9359c2f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDk3NDQsIm5iZiI6MTcxMDc0OTQ0NCwicGF0aCI6Ii8xNjA5ODAyNC8zMDA2NzUzMTctNWIzODBkMmEtOWQzMi00NjI3LWI2YjQtNzRmZDkzNTljMmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA4MTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmM4NTczMmE1NTU3ZjY2YjdiNmExOTUwNGY2MTJjOWE4NDliOWJjY2FlY2M5MmUyZWQ4NDAxNmY5OTM4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MjVavbSHWV4AVsxe5Yid_M6Cwfj3kwSM1JMFI-XOVuA"> [780.pdf](https://github.com/thuml/iTransformer/files/14092600/780.pdf)
> 
> 我在Mac mini M2上运行的算法。对脚本做了少量改动，把cuda换成了mps。类似这样： if torch.backends.mps.is_available():如果 torch.backends.mps.is_available(): device = torch.device("mps") 设备 = torch.device("mps")
> 
> 什么地方能看到你们官方的test_results目录的内容吗？

get the similar result on the testset

**Comment by mawenju203** [comment]
@ZDandsomSP 

> 您好，在查看了实验结果后，我们已经确认了您提到的问题。首先，这个仓库主要负责复现论文中的主要指标。我们还看到您重现了我们论文中报告的实验结果，因此我们很高兴我们的代码在您的环境中没有遇到任何基本问题。其次，exchage_rate 数据集被广泛认为缺乏平稳性，实际上很难预测。你提到的可视化现象在我们的实验环境中也发现了，但这实际上是所有深度网络方法的瓶颈。目前，它只能拟合这个非平稳序列的平均值。您可以可视化来自其他基线的一些结果来验证这一点。
> 
> <img alt="0fa3541fc41d9d3b2d118daba5b8705" width="491" src="https://private-user-images.githubusercontent.com/88132465/313969778-42674120-9cfb-4210-bc76-9cdc902b57f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDU1NjAsIm5iZiI6MTcyNTAwNTI2MCwicGF0aCI6Ii84ODEzMjQ2NS8zMTM5Njk3NzgtNDI2NzQxMjAtOWNmYi00MjEwLWJjNzYtOWNkYzkwMmI1N2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0N2Y3YWVmNjkxZTgxZjU5NzkyMmY5ODdmYTVlOTdiZGJkMjM5MzljM2ViN2I5YmRjMzA1ZjQ4ZDBkZTdjYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TxC2gggOXowIkC9w9ryL4pJW0KVbQSrliCKjQZCfjE4"><img alt="095983bc64e00576106a48c397c87e3" width="490" src="https://private-user-images.githubusercontent.com/88132465/313969825-4cbe871b-2c8a-4c00-b062-113efd3f9146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDU1NjAsIm5iZiI6MTcyNTAwNTI2MCwicGF0aCI6Ii84ODEzMjQ2NS8zMTM5Njk4MjUtNGNiZTg3MWItMmM4YS00YzAwLWIwNjItMTEzZWZkM2Y5MTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YzJlZDY3MDNhY2YxODE2ODA5MjExN2NhNmUwYjM4ZDlkZDU2ZGJlMmIwYTQzMmJiMzUzZDc2NDAyZjNhYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQt9y-AzFQDxWnHZSvvmriipov9BzCfKwUJyCMNI_lQ">
> 
> 此外，关于重现您提到的 Traffic 数据集效果的问题，请确保您的实验环境与我们的一致。我们在基于 x86 架构的 Ubuntu 服务器上进行了实验，并提供了以下日志输出： ![image](https://private-user-images.githubusercontent.com/88132465/313969226-0c52df2e-66bb-46e5-81a1-aa935b7ea86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDU1NjAsIm5iZiI6MTcyNTAwNTI2MCwicGF0aCI6Ii84ODEzMjQ2NS8zMTM5NjkyMjYtMGM1MmRmMmUtNjZiYi00NmU1LTgxYTEtYWE5MzViN2VhODZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMWQwODgwOWJlOWRhNmY2NjA5MjM5MjJmNWRlZWVkNDU5NGVkMTA4OTQ5ZjVmNGIyNTIzZDg3MmMxYTMxYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ZmrhDka7jvyhI91RWcrpuAowwgV5Kacd4PoDLQN87I)

您好，我对你所述的“exchage_rate 数据集被广泛认为缺乏平稳性”，这句话是什么意思？能详细解释一下吗？
