### ISSUE TITLE
预测结果不好

### ISSUE THREAD

**Issue by boris-lb** [thuml/iTransformer#55]
正常cuda环境，自定义数据集，使用src/iTransformer/scripts/multivariate_forecasting/Weather/iTransformer.sh的参数，改了预测输出的长度，mse和mae显示都很小，但是实际线上预测结果不好，部分结果如图，感觉模型只学到了一个均值，有什么优化的建议吗？

**Comment by boris-lb** [comment]
![Uploading 20240226103855.png…]()
![Uploading 20240226104123.png…]()

**Comment by boris-lb** [comment]
图片传不上来，这是训练日志结束部分：
	speed: 0.0260s/iter; left time: 195.1102s
	iters: 3500, epoch: 8 | loss: 0.1815589
	speed: 0.0261s/iter; left time: 193.4643s
	iters: 3600, epoch: 8 | loss: 0.1211413
	speed: 0.0262s/iter; left time: 190.9138s
Epoch: 8 cost time: 92.1232500076294
Epoch: 8, Steps: 3633 | Train Loss: 0.1963884 Vali Loss: 0.4524847 Test Loss: 0.0660085
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : yao_iTransformer_custom_M_ft96_sl48_ll48_pl512_dm8_nh2_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 14506
test shape: (14506, 1, 48, 14) (14506, 1, 48, 14)
test shape: (14506, 48, 14) (14506, 48, 14)
mse:0.06611385941505432, mae:0.13421496748924255

预测结果类似于[52](https://github.com/thuml/iTransformer/issues/52)里面的下面那张图像

**Comment by WenWeiTHU** [comment]
Hello, please try to adjust the hyperparameters according to the characteristics of your customized data, and consider the predictability of the data itself, etc.
