### ISSUE TITLE
Memory Footprint?

### ISSUE THREAD

**Issue by Atik-Ahamed** [thuml/iTransformer#56]
Dear Authors,
Your research is highly interesting. It was a great finding for time-series forecasting. We are very interested in this. However, regarding the memory footprint mentioned in figure 10 of the paper, we are a bit confused about how it is measured. Is there any code available to measure this? Or can you provide some instructions on how we can measure this? For example, does it include GPU-only memory consumption or GPU+RAM memory consumption?

Thank you in advance.

**Comment by WenWeiTHU** [comment]
Hello, we measure the GPU-only memory consumption under the stated configuration in our paper (See Appendix for the details).
