### ISSUE TITLE
train_loader invocation encountered "RuntimeError: stack expects each tensor to be equal size, but got [35, 34] at entry 0 and [0, 34] at entry 1"

### ISSUE THREAD

**Issue by alanz2015** [thuml/iTransformer#58]
Hi, 
I prepared a TS dataset, and use the following parameters:
export CUDA_VISIBLE_DEVICES=1

model_name=iTransformer

python -u run.py \
  --exp_name partial_train \
  --use_gpu True \
  --is_training 1 \
  --root_path ./dataset/stocks_trading/ \
  --data_path 002281-20240227.csv \
  --model_id Stock_5_1 \
  --model $model_name \
  --data custom \
  --features MS \
  --target priceDiff \
  --freq b \
  --checkpoints ./checkpoints/ \
  --label_len 34 \
  --seq_len 5 \
  --pred_len 1 \
  --e_layers 2 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 1 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 128 \
  --num_workers 0 \
  --itr 1

When execute 
File "/home/alanz/temp/iTransformer/experiments/exp_long_term_forecasting_partial.py", line 133, in train
    for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in enumerate(train_loader):
............
RuntimeError: stack expects each tensor to be equal size, but got [35, 34] at entry 0 and [0, 34] at entry 1

Any clue on the error? Thanks!

- Alan Zhang

**Comment by WenWeiTHU** [comment]
It seems unmatched batch size (especially the last batch in an epoch), please check the data file and try ‘drop_last=True’. Since this issue is less relative to the paper implementation, the issue will be closed.

**Comment by WenWeiTHU** [comment]
Since this issue is less relative to the paper implementation, the issue will be closed.
