### ISSUE TITLE
ValueError: could not convert string to float: '2020-01-01 00:20:00'

### ISSUE THREAD

**Issue by Terryjsz** [thuml/iTransformer#59]
when I run:  
train_loader, eval_loader, test_loader = get_loaders(weather_data, batch_size, n_train, n_eval, n_test, T=96, S=96)  
get error: ValueError: could not convert string to float: '2020-01-01 00:20:00' #59

**Comment by WenWeiTHU** [comment]
Please check the encoding of the csv file. Since this issue is less relative to the paper, the issue will be closed.
