### ISSUE TITLE
can we do predicting

### ISSUE THREAD

**Issue by ooOPPPPPS** [thuml/iTransformer#6]
In run.py I found train and test. Is there some where allowed us do predicting? thx

**Comment by WenWeiTHU** [comment]
Of course! You can set the ```arg.is_training=False``` after you have trained a model and just want to evaluate it.

**Comment by ooOPPPPPS** [comment]
Sorry，"test" refers to the part of the data set that deals with the test set, and "predicting" means predicting a trend in the future based on previously learned rules. For example, exp_main.py in fedformer and patchtst have a predict() after valid, train and test

**Comment by WenWeiTHU** [comment]
Thanks for your sharing, we will consider to incorporate it in the future.

**Comment by ZDandsomSP** [comment]
We‘ve add the predict function to the code, and you can try using it now!

**Comment by farazBhatti** [comment]
@ZDandsomSP can you please clearify how to do pridiction, i mean do_predction is inside is_training. How to use it ?can you give command arguments for doing prediction, please?
