### ISSUE TITLE
Question: Support for Dynamic Categorical Inputs in iTransformer

### ISSUE THREAD

**Issue by rd1886** [thuml/iTransformer#61]
Hi,

I am interested in using the iTransformer model for a project and had a question about its input capabilities. Does the iTransformer support dynamic categorical inputs? If so, could you provide some guidance or examples on how to implement this? I couldn't find any mention of this feature in the paper.

Thanks!

**Comment by GuYith** [comment]
I have a similar question, I want to use covariates in training. Does the iTransformer support dynamic covariates?  If so, could you provide some guidance or examples on how to implement this?

**Comment by WenWeiTHU** [comment]
Of course, we are in process now! You may be interested in our recent work where iTransformer is further enhanced with covariates for time series forecasting! 

[TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)

The code will also be released soon, please stay tuned!

**Comment by royzjq** [comment]
> Of course, we are in process now! You may be interested in our recent work where iTransformer is further enhanced with covariates for time series forecasting!
> 
> [TimeXer: Empowering Transformers for Time Series Forecasting with Exogenous Variables](https://arxiv.org/abs/2402.19072)
> 
> The code will also be released soon, please stay tuned!

四个月了，呜呜呜

**Comment by WenWeiTHU** [comment]
大家好，因为文章投稿的问题，TimeXer的代码还没有开源，后续开源后会尽快通知感兴趣的朋友们

**Comment by WenWeiTHU** [comment]
大家好！TimeXer将在这个仓库开源：https://github.com/thuml/TimeXer

**Comment by royzjq** [comment]
感谢！
