### ISSUE TITLE
无法重现论文中的结果

### ISSUE THREAD

**Issue by wangcheng0825** [thuml/iTransformer#62]
我尝试运行scripts/multivariate_forecasting/ECL/iTransformer.sh复原论文中的结果
<img width="2056" alt="image" src="https://github.com/thuml/iTransformer/assets/6059018/af0983b9-8952-456d-acee-c06318d9c743">

但是很遗憾，尝试了多次运行，loss与论文中的差距巨大
<img width="728" alt="image" src="https://github.com/thuml/iTransformer/assets/6059018/0a7dfc46-cd54-4eec-97c8-629d36eff72d">

我没有进行任何参数调整，想知道一下原因，谢谢

**Comment by ZDandsomSP** [comment]
![image](https://github.com/thuml/iTransformer/assets/88132465/7cf19d6c-98d4-4707-9cdd-af3fe8bc3c86)
您好，我们在我们的平台上重复了这个脚本的实验，结果与论文一致。
请您确认您的实验环境（包括Python版本，Torch版本）与我们提供的requirements一致，如果实在需要的话可以联系我们提供ckpt

**Comment by VEWOXIC** [comment]
那这是否意味着模型是不鲁棒的/汇报的是cherrypick过的结果

**Comment by WenWeiTHU** [comment]
> 那这是否意味着模型是不鲁棒的/汇报的是cherrypick过的结果

您好，可以参考附录A.2与C，此处包括了我们的参数确定方式与error bar
