### ISSUE TITLE
How to visualize the results?

### ISSUE THREAD

**Issue by gaochenxiai** [thuml/iTransformer#63]
![屏幕截图 2024-03-22 153903](https://github.com/thuml/iTransformer/assets/115993328/730f17e2-a14d-4e5c-8e20-38946c868201)

**Comment by gaochenxiai** [comment]
I did not find the drawing module.

**Comment by YEKAI-2022** [comment]
> ![屏幕截图 2024-03-22 153903](https://private-user-images.githubusercontent.com/115993328/315924393-730f17e2-a14d-4e5c-8e20-38946c868201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODc2NjEsIm5iZiI6MTcxMTI4NzM2MSwicGF0aCI6Ii8xMTU5OTMzMjgvMzE1OTI0MzkzLTczMGYxN2UyLWExNGQtNGU1Yy04ZTIwLTM4OTQ2Yzg2ODIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzM2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OThkNzkzYzVhNzQwMTQ0NDZlZjQ2NDEzZmQxYTEwZDAzMDNkYzc2OGVhYWVmOWI5NmZhN2QxNDNjNjEwODVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._w7nIxY5Bh9SYkx785OJmjeOCPq9mydNRwNNZEHKoHE)

I also want to know how the above picture is visualized. Can you provide the source code:

**Comment by YEKAI-2022** [comment]
Can you give me some guidance on how to draw the above prediction chart?

**Comment by WenWeiTHU** [comment]
Hello, please refer to the ```tools.py``` under the ```utils``` folder.

**Comment by YEKAI-2022** [comment]
> Hello, please refer to the `tools.py` under the `utils` folder.

代码中生成的.pdf文件可视化效果和你论文提供的不一样，这个怎么解决，期待你的答复，谢谢！
