### ISSUE TITLE
如何获得更优的模型参数

### ISSUE THREAD

**Issue by LeonTing1010** [thuml/iTransformer#69]
我们正在使用iTransformer应用业务系统，但是一直无法获得比较满意的结果，请问如何调整模型的参数可以获得较好的结果，可以分享下参数调整的经验吗？非常感谢

**Comment by WenWeiTHU** [comment]
很高兴iTransformer作为深度模型应用于业务系统，方便的话能否提供若干场景细节，例如预测任务，特征属性等

**Comment by hqwl159** [comment]
> 我们正在使用iTransformer应用业务系统，但是一直无法获得比较满意的结果，请问如何调整模型的参数可以获得较好的结果，可以分享下参数调整的经验吗？非常感谢

你好，我也准备应用到业务系统，请问你们参数调整有好结果了吗？是不是数据集本身清洗问题？

**Comment by LeonTing1010** [comment]
> 很高兴iTransformer作为深度模型应用于业务系统，方便的话能否提供若干场景细节，例如预测任务，特征属性等

我们是基于gluonts做金融数据的时序分析和量化交易，比如我们有一些交易数据（'流通市值', '成交量', '振幅'等等），根据这些交易数据做价格的预测和分析，请问我们在使用iTransformer时需要注意些什么，如何调优相关参数，谢谢

**Comment by hqwl159** [comment]
您的邮件已收到，我会尽快进行回复。--from hQing

**Comment by kwuking** [comment]
> > 很高兴iTransformer作为深度模型应用于业务系统，方便的话能否提供若干场景细节，例如预测任务，特征属性等
> 
> 我们是基于gluonts做金融数据的时序分析和量化交易，比如我们有一些交易数据（'流通市值', '成交量', '振幅'等等），根据这些交易数据做价格的预测和分析，请问我们在使用iTransformer时需要注意些什么，如何调优相关参数，谢谢

你好 请问您是将itransformer应用在金融量化交易的场景嘛，您现在遇到的问题就是如何调优模型参数吗？

**Comment by hqwl159** [comment]
您的邮件已收到，我会尽快进行回复。--from hQing
