### ISSUE TITLE
论文疑惑

### ISSUE THREAD

**Issue by yangguang760** [thuml/iTransformer#7]
作者您好！
首先感谢您的工作，文章逻辑清晰，源码组织规整！
拜读文章时有两个疑问向您请教。
第一：
在 4.2 iTransformers Generality 的 Variate generalization部分，文章提到
Firstly, benefiting from the flexibility of the
number of input tokens, the amount of variate channels is no longer restricted and thus feasible to vary
from training and inference. 以及后续的Figure 5
我的理解此处的variate是指时间序列的维度，即  # N: number of variate (tokens), 也即参数集里的enc_in，Figure 5 的实验则是隐藏80%的维度后做对比实验；
如果我的理解没错的话，请问如何实现训练和推断时使用不一样的数据维度？在embedding和FFN层面的处理我可以理解（参数形状和数据维度无关），但是在自注意力层面，Q, K, V 的形状是 N*Dk, 如果N在训练和推断时不一致，这部分参数如何在训练和推断时共享？

第二：
如果想针对三维数据（时序，特征，实体）而非二维数据（时序，特征）使用，请问如何处理比较合适?

感谢解惑，谢谢！

**Comment by WenWeiTHU** [comment]
您好，感谢您的关注！

您的理解是正确的。在实现上，Transformer是可以接受变长Token输入的，除了在Embedding和FFN层，在Attetion中的W_k, W_q, W_v也是独立做在每个Token上的（映射：d_model -> d_k），和Token个数N无关。

您可以尝试Encoder-only的传统Transformer，其在推理时就可用不同于训练时的时间步(Time Step as Token)。

在Inverted Transformer中，这种推理任意Token的能力则反映在了变量维（Variate as Token）。实际上Attetion中的W_k, W_q, W_v旨在从各种Token中学习如何提取特征，服务Token之间的相关性建模，这是一种变量无关的学习能力，从而这些参数具有泛化到未知的变量上的潜力，我们的实验正是验证了这一点！

代码实现可以参考scripts/variate_generalization下的脚本，其中训练时用到的enc_in都是小于这个数据集的变量数的。而在推理时，推理的是全量变量。

<img width="604" alt="image" src="https://github.com/thuml/iTransformer/assets/39073236/dde236ff-54b5-46b8-93c3-c557f0be7185">
<img width="569" alt="image" src="https://github.com/thuml/iTransformer/assets/39073236/5daa3bf0-9678-4344-ac6c-63630bf78e72">

**Comment by WenWeiTHU** [comment]
您还提到一个更高维度的问题，这也是目前我们正在尝试的的方向！这个问题的关键一般是如何组织这些Token以及利用他们的先验，或许可以借鉴一时空预测模型的思路，例如 [Corrformer](https://github.com/thuml/Corrformer)

**Comment by yangguang760** [comment]
明白了，感谢解惑！
