### ISSUE TITLE
seq_len取值小于48时，代码无法运行

### ISSUE THREAD

**Issue by okaygogo** [thuml/iTransformer#71]
在代码运行时，当输入长度（seq_len）取值小于48时，数据可以载入，但是模型运行就会报错，RuntimeError: Trying to resize storage that is not resizable.
这是因为什么呢？如何改进？期待您的解答

**Comment by hbwzj** [comment]
> 在代码运行时，当输入长度（seq_len）取值小于48时，数据可以载入，但是模型运行就会报错，RuntimeError： Trying to resize storage that is not respensable . 这是因为什么呢？如何改进？期待您的解答

因为那个-label_len', type=int, default=48和你的输入长度一样了呀，你试着改成小一倍试试
