### ISSUE TITLE
有关使用或不使用.sh 文件的训练时间和内存使用率的问题

### ISSUE THREAD

**Issue by syrGitHub** [thuml/iTransformer#74]
当我运行.sh文件时，随着命令的运行，速度会突然变慢，CPU的利用率也很高，但是如果不采用.sh 脚本，每次单独运行命令行速度却是正常的，请问作者大大们知道是什么原因吗？
![image](https://github.com/thuml/iTransformer/assets/31035074/bcff1c8e-1246-494b-9daf-f5dbe06f5517)
vs
![image](https://github.com/thuml/iTransformer/assets/31035074/7308c1eb-338e-4398-80ee-38f94781c461)
CUP 使用情况
![image](https://github.com/thuml/iTransformer/assets/31035074/f70e5074-36fb-44aa-be13-52e35a4d4f24)

**Comment by kwuking** [comment]
你好 请问你是使用cpu运行的脚本嘛，建议使用GPU进行运行，这可以有效的加速训练和测试。
