### ISSUE TITLE
data_loader.py文件的疑问

### ISSUE THREAD

**Issue by Sunlandis** [thuml/iTransformer#79]
您好，在这个文件这定义类有这么一个判断操作：
if self.timeenc == 0:
            df_stamp['month'] = df_stamp.date.apply(lambda row: row.month, 1)
            df_stamp['day'] = df_stamp.date.apply(lambda row: row.day, 1)
            df_stamp['weekday'] = df_stamp.date.apply(lambda row: row.weekday(), 1)
            df_stamp['hour'] = df_stamp.date.apply(lambda row: row.hour, 1)
            df_stamp['minute'] = df_stamp.date.apply(lambda row: row.minute, 1)
            df_stamp['minute'] = df_stamp.minute.map(lambda x: x // 15)
            data_stamp = df_stamp.drop(['date'], 1).values
        elif self.timeenc == 1:
            data_stamp = time_features(pd.to_datetime(df_stamp['date'].values), freq=self.freq)
            data_stamp = data_stamp.transpose(1, 0)
这段判断条件中为什么没有else？不知道有没有具体的用意？

**Comment by WenWeiTHU** [comment]
您好，这快没有特殊用意，应该是一个历史遗留问题，详情可移步[tslib](https://github.com/thuml/Time-Series-Library)

**Comment by Sunlandis** [comment]
感谢！
