### ISSUE TITLE
关于label_len参数的疑问

### ISSUE THREAD

**Issue by Sunlandis** [thuml/iTransformer#80]
您好，请问在run.py代码中 对label_len参数有一个标注：# no longer needed in inverted Transformers
据我所了解label_len是计算损失函数时所用的序列长度，是为了针对特定的预测范围和需求。那为什么在iTransformer这一倒置操作以后就不需要label_len了呢？但是在我跑的traffic预测任务的sh文件中对iTransformer的参数设置 没有提及label_len，那就是采用默认的48，与pred_len的96也不吻合，所以我不是很理解iTransformer不需要label_len的含义，是指不需要调整这个超参数吗？那为什么48比较好而不是和pred_len 一致呢？请指教！！🙏🙏🙏

**Comment by WenWeiTHU** [comment]
您好，请参考：https://github.com/thuml/Time-Series-Library/issues/49
