### ISSUE TITLE
Multi-Label Prediction

### ISSUE THREAD

**Issue by TomKoester** [thuml/iTransformer#83]
Hello, 

is there a way to adapt the iTransformer model into a Multi-Label Prediction like SNGP?

**Comment by WenWeiTHU** [comment]
Hi, could you provide more details about this method?

**Comment by TomKoester** [comment]
In this Paper https://arxiv.org/pdf/2006.10108 are more details. I want to transform the iTransformer from deterministic into a probalistic output so i can use it for multilabel prediction. In my case: i have 300 charging stations and want to predict when/which will they be occupied/free. I already tried to make the activation function a simple sigmoid layer but i dont know if this is the right way.

**Comment by TomKoester** [comment]
@WenWeiTHU Hey, i were able to apply Gaussian as the last Layer to get the Probabilties. Can you give me an advice how i can apply the Spectral Normalization to your implemented Layers and where its necessary?
