### ISSUE TITLE
代码疑问 exp_long_term_forecasting.py

### ISSUE THREAD

**Issue by Sunlandis** [thuml/iTransformer#84]
您好，exp_long_term_forecasting.py中45行 batch_y在验证的时候没有放入设备，但是下面batch_y_mark却放入设备了，猜测是否是45行最后漏写了.to(self.device)？ 还是有意为之呢？有什么设计作用呢？

**Comment by WenWeiTHU** [comment]
感谢您的建议，此处是因为推理是在cpu上进行的，所以不需要移入到gpu等设备上，并不影响实验结果。

为保证代码一致，我们已经修复了这个issue：https://github.com/thuml/iTransformer/commit/257d5c39e1a8baa27904b4215a5459674249d4ab
