### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Kerry-zzz** [thuml/iTransformer#86]
你好，我复现代码的时候为什么只能跑通iTransformer、iInformer等倒置embed的模型，当我想尝试将model改为Transformer或者informer时就会出现RuntimeError: Given groups=1, weight of size [512, 7, 3], expected input[32, 321, 98] to have 7 channels, but got 321 channels instead的错误
我也尝试去解决，没有成功，请问问题出现在哪里呢？

**Comment by WenWeiTHU** [comment]
Thanks for your notice! we will check it out and fix it soon.

**Comment by ZDandsomSP** [comment]
Hello, we understand that you are having an issue with our warehouse code, but we did not trigger the error you mentioned when running a non inverted model. Could you please provide more error information to assist in resolving the issue?

**Comment by Kerry-zzz** [comment]
Hello, I just retested your code again, as shown in the picture. Can only these five model options be selected in the run.py file? But I saw in exp_basic.py that it is possible to choose models that are not inverted (such as Transformer), so I wanted to use the Transformer model to compare the experimental results, but the results are shown in the figure and cannot be run. May I ask where I went wrong?Looking fo
![1](https://github.com/thuml/iTransformer/assets/104133006/511b9cbe-cdca-4a9a-8183-fb29c273696a)
![2](https://github.com/thuml/iTransformer/assets/104133006/67752d4d-5362-4148-8ad1-39975ab64aee)
![3](https://github.com/thuml/iTransformer/assets/104133006/622bfbed-32bc-4c37-a97f-26642f3bab4b)
![4](https://github.com/thuml/iTransformer/assets/104133006/019f52cd-84d3-4f09-8a36-063920521120)
rward to your reply very much, thank you @ZDandsomSP

**Comment by ZDandsomSP** [comment]
Based on your feedback, you should have directly executed the `run.py` file, but we have provided a complete [script](https://github.com/thuml/iTransformer/blob/main/scripts/boost_performance/ECL/iTransformer.sh) for the experiments involved in the paper, which includes some necessary parameters. The screenshot you provided lacks parameters such as `-- enc_in`. Please read our readme and experimental script before continuing testing, or directly execute our script and make modifications based on it to experiment

**Comment by Kerry-zzz** [comment]
thank you



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZDand ***@***.***&gt;
发送时间: 2024年6月14日 12:04
收件人: thuml/iTransformer ***@***.***&gt;
抄送: Kerry-zzz ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [thuml/iTransformer] 代码问题 (Issue #86)





 
Based on your feedback, you should have directly executed the run.py file, but we have provided a complete script for the experiments involved in the paper, which includes some necessary parameters. The screenshot you provided lacks parameters such as -- enc_in. Please read our readme and experimental script before continuing testing, or directly execute our script and make modifications based on it to experiment
