### ISSUE TITLE
预测曲线问题

### ISSUE THREAD

**Issue by Kerry-zzz** [thuml/iTransformer#90]
您好，我复现论文时候在test_result文件里得到的预测曲线是橙色的prediction曲线先出现，GroundTruth曲线后出现，但是我看见论文里面的预测曲线橙色的是GroundTruth曲线在前，Prediction预测曲线后面才出现，请问是哪里有问题呢？

![image](https://github.com/thuml/iTransformer/assets/104133006/c92f3e01-ba1c-48e9-86b5-88ab92ad4a28)
![image](https://github.com/thuml/iTransformer/assets/104133006/ab47d3f6-963d-4d57-8879-4955d839ca5e)

**Comment by WenWeiTHU** [comment]
看上去是两个不同的输入，能提供更具体的描述吗？

**Comment by Kerry-zzz** [comment]
带有iTransformer标识的图片是原论文里面的图片，然后第一张图是我在复现论文时实验结果Test_result文件里的预测图片，我没有改过代码，然后我发现两个图片曲线的前半部分一个代表GroundTruth曲线，但为什么实验做出来的曲线前半部分显示是Prediction呀？谢谢您的回复。

**Comment by WenWeiTHU** [comment]
应该是画曲线的顺序出了问题，我们会尽快修复
