### ISSUE TITLE
尝试复现和改进时结果出现问题

### ISSUE THREAD

**Issue by bigdata0** [thuml/iTransformer#91]
复现论文数据在预测PEMS时原论文采用的预测步长描述是12,24,48,96，而itransformer实际跑出来的mse和mae结果只能和12,24,36,48步长的结果比较吻合，请问是论文中数据的结果描述有问题吗，期待您的回复。
举例：
![H}Z2069~ }RTCMBP$(KN4(A](https://github.com/thuml/iTransformer/assets/88190033/180950c3-7d0b-4e24-8267-ec77501d8b51)
图为原项目复现PEMS03数据集输入96步预测48步的结果，在4090上完成。
![image](https://github.com/thuml/iTransformer/assets/88190033/49a7b4c5-075f-427e-9ecb-e1aa8e82f2a6)
使用的是提供的脚本，但并没有达到48步应有的结果反而和预测96步的结果较为吻合。

**Comment by bigdata0** [comment]
![image](https://github.com/thuml/iTransformer/assets/88190033/4c7a16ed-b909-4638-ac88-5e02d88c03be)
to同时论文正文中的描述为12,24,36,48步的预测，经过计算和附录中给出的结果均值一致，请问是附录提供的结果中描述有误吗，期待您的回复

**Comment by WenWeiTHU** [comment]
> ![image](https://private-user-images.githubusercontent.com/88190033/341091044-4c7a16ed-b909-4638-ac88-5e02d88c03be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjIzNjgsIm5iZiI6MTcxODg2MjA2OCwicGF0aCI6Ii84ODE5MDAzMy8zNDEwOTEwNDQtNGM3YTE2ZWQtYjkwOS00NjM4LWFjODgtNWUwMmQ4OGMwM2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA1NDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYTJhMDBjOTBmYTFmN2FmODdjY2NjYWMwNzVlMjhhYmQ2ZTI5OTgzZTI0N2ViNTY3OGQwMDFkYjdhNmQwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7jJKYcqByFhm9Z76B9oLquMCMCdZKQuxlkua2PoKYKc) to同时论文正文中的描述为12,24,36,48步的预测，经过计算和附录中给出的结果均值一致，请问是附录提供的结果中描述有误吗，期待您的回复

你好，此处填写有误，我们会尽快更新arxiv。Move to the related issue: https://github.com/thuml/iTransformer/issues/64

**Comment by bigdata0** [comment]
> 您好，我想请问一下数据集csv里面的的ot列代表什么呀？谢谢！

input-Multi output-Single也就是多变量输入预测单变量的时候，OT是需要预测的单变量列，多变量预测多变量则不需要特别关注这一列。
