### ISSUE TITLE
ValueError: non-broadcastable output operand with shape (3,1) doesn't match the broadcast shape (3,5)

### ISSUE THREAD

**Issue by warmful-sun** [thuml/iTransformer#92]
作者你好，我在进行MS预测时遇到了这个问题：
ValueError: non-broadcastable output operand with shape (3,1) doesn't match the broadcast shape (3,5)
我的总变量数为5，参数设置跑M多变量预测的时候没有问题。这是因为什么呢？参数设置有问题么？

**Comment by WenWeiTHU** [comment]
Hi, please refer to [the relevant issue](https://github.com/thuml/iTransformer/issues/19).
