### ISSUE TITLE
交通数据复现

### ISSUE THREAD

**Issue by dazhzh** [thuml/iTransformer#94]
<img width="359" alt="截屏2024-06-24 16 30 03" src="https://github.com/thuml/iTransformer/assets/144420989/c6090b0c-9469-48e8-a5e9-6379bad9358f">
为什么我的结果比论文里要好

**Comment by bigdata0** [comment]
改参数了改结构了或者实验环境不一样，相同配置的卡相同的参数一般也会有细微的差距
