### ISSUE TITLE
自回归任务问题的请教

### ISSUE THREAD

**Issue by teemohold** [thuml/iTransformer#96]
作者您好，看了您的iTransformer受到很大启发。
我现在所做的任务是一个自回归性质的任务，就是1,2预测3， 1,2,3预测4这样。
那请问iTransformer这个架构能否用于这种自回归式的任务呢？

**Comment by WenWeiTHU** [comment]
您好，可以参考我们最近的两个工作，预测方式均为自回归式：
* Timer: https://github.com/thuml/Large-Time-Series-Model
* AutoTimes: https://github.com/thuml/AutoTimes

**Comment by teemohold** [comment]
感谢



Mingliang Hou, Postdoc Researcher

Guangdong Institute of Smart Education & TAL

Email: ***@***.***

________________________________
发件人: Yong Liu ***@***.***>
发送时间: 2024年7月14日 15:05
收件人: thuml/iTransformer ***@***.***>
抄送: Houcaicai2.0 ***@***.***>; Author ***@***.***>
主题: Re: [thuml/iTransformer] 自回归任务问题的请教 (Issue #96)


您好，可以参考我们最近的两个工作，预测方式均为自回归式：

  *   Timer: https://github.com/thuml/Large-Time-Series-Model
  *   AutoTimes: https://github.com/thuml/AutoTimes

―
