### ISSUE TITLE
关于预测值与真实值的问题

### ISSUE THREAD

**Issue by shentaoashentao** [thuml/iTransformer#97]
请问，运行完程序之后，在result文件夹下生成的pred.npy、true.npy。如何将pred.npy、true.npy里的内容还原到原始真实数据与预测值？因为npy文件中的值存在负值。

**Comment by Wjxl2020** [comment]
请问是怎么解决的，我做预测任务后输出的也是负数，是指的与真实值的误差吗

**Comment by mawenju203** [comment]
请问这个问题解决了吗

**Comment by ambitious121** [comment]
> 请问这个问题解决了吗
Hello, I also have this question, how to solve this problem

**Comment by Xxlx5649** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by ambitious121** [comment]
> 我也遇到了这个问题，请问解决了吗

解决了在配置文件中设置--inverse就可以
