### ISSUE TITLE
How can i predict multivariate with multivariate

### ISSUE THREAD

**Issue by TomKoester** [thuml/iTransformer#99]
Hey,

How can i predict multivariate with multivariate? Where do i have to add the Targetfeatures in which format?
The reason im asking is the flag  --target.  In the description it says: "target feature in S or MS task". Now we have M task. How does the program know what my target features in my data are?

**Comment by WenWeiTHU** [comment]
Hi, please take a look at [the relevant issue](https://github.com/thuml/iTransformer/issues/19)

**Comment by TomKoester** [comment]
okay, i understand that i have to use flagbits to mark my target variables, right? Can you give me an short example how to use it? @WenWeiTHU
